export const HOOK_EVENTS = [
  "PreToolUse",
  "PostToolUse",
  "PostToolUseFailure",
  "SessionStart",
  "SessionEnd",
  "PermissionRequest",
  "UserPromptSubmit",
  "Notification",
  "SubagentStart",
  "SubagentStop",
  "Stop",
  "StopFailure",
  "ConfigChange",
  "PreCompact",
  "PostCompact",
  "InstructionsLoaded",
  "WorktreeCreate",
  "WorktreeRemove",
  "Elicitation",
  "ElicitationResult",
  "TeammateIdle",
  "TaskCompleted",
] as const;

export type HookEvent = (typeof HOOK_EVENTS)[number];

export const HOOK_EVENT_DESCRIPTIONS: Record<HookEvent, string> = {
  PreToolUse: "Trước khi công cụ chạy",
  PostToolUse: "Sau khi công cụ chạy thành công",
  PostToolUseFailure: "Sau khi công cụ thất bại",
  SessionStart: "Khi phiên bắt đầu hoặc tiếp tục",
  SessionEnd: "Khi phiên kết thúc",
  PermissionRequest: "Khi hộp thoại quyền xuất hiện",
  UserPromptSubmit: "Trước khi xử lý đầu vào người dùng",
  Notification: "Khi thông báo được gửi",
  SubagentStart: "Khi một subagent được tạo",
  SubagentStop: "Khi một subagent hoàn tất",
  Stop: "Khi Claude trả lời xong",
  StopFailure: "Khi một lượt kết thúc với lỗi API",
  ConfigChange: "Khi file cấu hình thay đổi",
  PreCompact: "Trước khi nén ngữ cảnh",
  PostCompact: "Sau khi nén ngữ cảnh",
  InstructionsLoaded: "Khi file CLAUDE.md được nạp",
  WorktreeCreate: "Khi worktree được tạo",
  WorktreeRemove: "Khi worktree bị xoá",
  Elicitation: "Khi MCP yêu cầu nhập từ người dùng",
  ElicitationResult: "Khi người dùng phản hồi MCP",
  TeammateIdle: "Khi một agent trong nhóm ở trạng thái nhàn rỗi",
  TaskCompleted: "Khi một tác vụ được đánh dấu hoàn tất",
};
